/* Prototype-only profile overrides. No collection, publication or production writes. */
window.buildEntityProfiles = ({getCompanies, getQuery, refresh, escape, safeURL}) => {
  const $=s=>document.querySelector(s), key='berry-design-editable-profiles-v1';
  let scopedCompanyId='', state={companies:{},people:{}}, currentPerson='mention-marc-werner', onlyHighlighted=false, session=0, editContext=null, logoDraft='', logoLoading=false;
  const channels=[['website','Website','https://…'],['linkedin','LinkedIn','https://www.linkedin.com/…'],['instagram','Instagram','@handle or full URL'],['x','X / Twitter','@handle or full URL'],['facebook','Facebook','Full profile URL'],['youtube','YouTube','Full channel URL']];
  const seeds=[
    {id:'mention-marc-werner',name:'Marc Werner',role:'Chief executive — June 2026 source mention',companyId:'company-costa-group-holdings',notes:'Named in the BluGenix article published June 8, 2026. This is a historical source mention; the current role and social accounts have not been verified.',source:'https://www.producereport.com/article/costa-launches-blugenix-5-blueberry-varieties-suited-yunnan',origin:'Historical source mention',contacts:{}},
    {id:'mention-leon-van-biljon',name:'Leon Van Biljon',role:'Regional director, Costa Berry International — source mention',companyId:'company-costa-group-holdings',notes:'Named in the BluGenix article published June 8, 2026. The source describes a regional director role. Current affiliation and social accounts need review.',source:'https://www.producereport.com/article/costa-launches-blugenix-5-blueberry-varieties-suited-yunnan',origin:'Historical source mention',contacts:{}}
  ];
  try{const x=JSON.parse(localStorage.getItem(key)||'{}');if(x.version===1&&x.companies&&x.people)state={companies:x.companies,people:x.people};}catch{}
  const people=()=>[...new Map([...seeds,...Object.values(state.people)].map(p=>[p.id,p])).values()];
  const companyProfile=c=>({...c,contacts:{...c.contacts,...state.companies[c.id]?.contacts},logo:state.companies[c.id]?.logo??c.logo??'',edited:!!state.companies[c.id]});
  function channelURL(kind,value){const v=String(value||'').trim();if(['instagram','x'].includes(kind)&&/^@[a-zA-Z0-9_.]+$/.test(v))return `https://${kind==='x'?'x.com':'www.instagram.com'}/${encodeURIComponent(v.slice(1))}`;return safeURL(v);}
  function links(p){const rows=channels.filter(([k])=>channelURL(k,p.contacts?.[k]));return `<div class="profile-channel-links">${rows.map(([k,label])=>`<a href="${escape(channelURL(k,p.contacts[k]))}" target="_blank" rel="noopener noreferrer">${escape(label)} ↗</a>`).join('')||'<span>No website or social links recorded yet.</span>'}</div>`;}
  function logo(c,large=false){const p=companyProfile(c), src=/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(p.logo)?p.logo:safeURL(p.logo);return `<span class="company-logo ${large?'large':''}"><span>${escape(c.name.split(' ').map(x=>x[0]).join('').slice(0,2))}</span>${src?`<img src="${escape(src)}" alt="${escape(c.name)} logo" referrerpolicy="no-referrer" loading="lazy">`:''}</span>`;}
  function companyDetails(c){const p=companyProfile(c);return `<section class="company-contact-block"><div><strong>Website & social profiles</strong><button data-edit-company="${escape(c.id)}">Edit details & logo</button></div>${links(p)}<p>${p.edited?'User-edited profile details':'Stored directory metadata · links are not independently verified'}</p></section>`;}
  function write(next){try{localStorage.setItem(key,JSON.stringify({version:1,...next}));state=next;return true;}catch{$('#profile-error').textContent='Could not save to browser storage. If uploading a logo, try a smaller image.';return false;}}
  function companyPeopleMarkup(){return `<section class="company-people"><div class="people-tab-toolbar"><h3>People at this company</h3><button id="add-person">+ Add person</button><button id="people-highlight-filter" aria-pressed="false">Highlighted only</button><span id="people-count"></span></div><div id="people-rows"></div><div id="person-profile"></div></section>`;}
  function renderPeople(companyId=scopedCompanyId){
    if(!$('#people-rows'))return;scopedCompanyId=companyId;
    const all=people().filter(p=>p.companyId===companyId), query='';
    const rows=all.filter(p=>(!onlyHighlighted||p.highlighted)&&(!query||[p.name,p.role,getCompanies().find(c=>c.id===p.companyId)?.name||''].join(' ').toLowerCase().includes(query))).sort((a,b)=>Number(!!b.highlighted)-Number(!!a.highlighted)||a.name.localeCompare(b.name));
    if(!rows.some(p=>p.id===currentPerson))currentPerson=rows[0]?.id;
    $('#people-count').textContent=`${rows.length} people · ${all.filter(p=>p.highlighted).length} highlighted`;
    $('#people-highlight-filter').setAttribute('aria-pressed',String(onlyHighlighted));
    $('#people-rows').innerHTML=rows.length?rows.map(p=>`<article class="person-row ${p.id===currentPerson?'selected':''}"><button data-person="${escape(p.id)}"><span class="person-avatar">${escape(p.name.split(' ').map(x=>x[0]).join('').slice(0,2))}</span><span><strong>${escape(p.name)}</strong><small>${escape(p.role||'Role not recorded')}</small><em>${escape(getCompanies().find(c=>c.id===p.companyId)?.name||'Company not linked')}</em></span></button><button data-highlight-person="${escape(p.id)}" aria-pressed="${!!p.highlighted}" aria-label="${p.highlighted?'Unhighlight':'Highlight'} ${escape(p.name)}">${p.highlighted?'★':'☆'}</button></article>`).join(''):'<div class="empty"><h3>No matching people.</h3><p>Adjust your search or add a person.</p></div>';
    const p=all.find(x=>x.id===currentPerson);if(!p){$('#person-profile').innerHTML='<div class="empty">Select or add a person to view their profile.</div>';return;}
    const company=getCompanies().find(c=>c.id===p.companyId);
    $('#person-profile').innerHTML=`<header class="company-profile-header"><span class="eyebrow">PERSON · ${escape(p.origin)}</span><h2>${escape(p.name)}</h2><p class="person-role">${escape(p.role||'Role not recorded')}</p><div class="company-profile-actions"><button data-edit-person="${escape(p.id)}">Edit person & links</button><button class="person-highlight" data-highlight-person="${escape(p.id)}" aria-pressed="${!!p.highlighted}">${p.highlighted?'★ Highlighted':'☆ Highlight person'}</button></div></header><div class="person-profile-body"><section class="company-section"><h3>Profiles & social handles</h3>${links(p)}<p class="company-gap">Links and handles can always be entered or corrected manually.</p></section><section class="company-section"><h3>Company connection</h3>${company?`<button class="person-company" data-view="companies" data-entity="${escape(company.id)}">${logo(company)}${escape(company.name)} →</button>`:'<p class="company-gap">No company linked yet.</p>'}</section><section class="company-section"><h3>Context & provenance</h3><p class="company-description">${escape(p.notes||'No context added yet.')}</p>${safeURL(p.source)?`<a class="person-source" href="${escape(safeURL(p.source))}" target="_blank" rel="noopener noreferrer">Read source mention ↗</a>`:''}<p class="company-gap">${p.origin==='Historical source mention'?'Historical mention awaiting review; this does not verify a current role or account.':'User-entered profile metadata; this does not promote source claims to trusted facts.'}</p></section></div>`;
  }
  function openEditor(kind,id=''){
    session++;editContext={kind,id};logoLoading=false;
    const c=getCompanies().find(x=>x.id===id),p=kind==='company'?companyProfile(c):people().find(x=>x.id===id)||{name:'',role:'',companyId:scopedCompanyId,notes:'',contacts:{}};logoDraft=p.logo||'';
    $('#profile-editor-title').textContent=kind==='company'?`Edit ${c.name}`:id?`Edit ${p.name}`:'Add a person';
    $('#profile-editor-body').innerHTML=`<p class="editor-note">Manual edits stay in this browser for the preview. Future AI suggestions must show their source and be reviewed; they must not overwrite your edits.</p><form id="entity-profile-form">${kind==='person'?`<div class="edit-field-grid"><label>Name<input id="person-name" value="${escape(p.name)}" maxlength="120" required></label><label>Role / title<input id="person-role" value="${escape(p.role||'')}" maxlength="180"></label><label class="wide">Company<select id="person-company"><option value="">No company linked</option>${getCompanies().slice().sort((a,b)=>a.name.localeCompare(b.name)).map(c=>`<option value="${escape(c.id)}" ${c.id===p.companyId?'selected':''}>${escape(c.name)}</option>`).join('')}</select></label></div>`:`<section class="logo-edit"><div id="logo-edit-preview">${logo(c,true)}</div><div><label>Upload company logo<input id="logo-upload" type="file" accept="image/png,image/jpeg,image/webp"></label><small>PNG, JPEG or WebP · up to 2 MB</small><label>Or use a logo URL<input id="logo-url" value="${escape(safeURL(logoDraft))}" placeholder="https://…"></label><button type="button" id="remove-logo">Remove logo</button><p id="logo-error" role="alert"></p></div></section>`}<div class="edit-field-grid">${channels.map(([k,label,hint])=>`<label>${label}<input data-contact="${k}" value="${escape(p.contacts?.[k]||'')}" placeholder="${escape(hint)}" maxlength="1000"></label>`).join('')}</div>${kind==='person'?`<label class="editor-notes-label">Notes / context<textarea id="person-notes" maxlength="2000" rows="3">${escape(p.notes||'')}</textarea></label>`:''}<p id="profile-error" role="alert"></p><div class="editor-save"><button type="submit">Save details</button><button type="button" data-close>Cancel</button>${(kind==='company'?state.companies[id]:state.people[id]&&seeds.some(x=>x.id===id))?'<button type="button" data-restore-profile>Restore stored details</button>':''}</div></form>`;
    $('#profile-editor').showModal();
  }
  document.addEventListener('error',e=>{if(e.target.matches?.('.company-logo img'))e.target.hidden=true;},true);
  document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
    if(b.dataset.editCompany)openEditor('company',b.dataset.editCompany);
    if(b.id==='add-person')openEditor('person');
    if(b.dataset.editPerson)openEditor('person',b.dataset.editPerson);
    if(b.dataset.person){currentPerson=b.dataset.person;renderPeople();if(matchMedia('(max-width:900px)').matches)$('#person-profile').scrollIntoView({block:'start'});}
    if(b.id==='people-highlight-filter'){onlyHighlighted=!onlyHighlighted;renderPeople();}
    if(b.dataset.highlightPerson){const p=people().find(x=>x.id===b.dataset.highlightPerson);const next={...state,people:{...state.people,[p.id]:{...p,highlighted:!p.highlighted}}};try{localStorage.setItem(key,JSON.stringify({version:1,...next}));state=next;renderPeople();}catch{document.querySelector('#toast').textContent='Browser storage is unavailable. The highlight was not saved.';}}
    if(b.hasAttribute('data-restore-profile')&&editContext){const bucket=editContext.kind==='company'?'companies':'people';const entries={...state[bucket]};delete entries[editContext.id];if(write({...state,[bucket]:entries})){$('#profile-editor').close();refresh();renderPeople();}}
    if(b.id==='remove-logo'){logoDraft='';$('#logo-url').value='';$('#logo-upload').value='';$('#logo-edit-preview').innerHTML='<span class="logo-removed">No logo selected</span>';}
  });
  $('#profile-editor').addEventListener('close',()=>{session++;editContext=null;});
  $('#profile-editor-body').addEventListener('change',async e=>{
    if(e.target.id==='logo-url'){logoDraft=e.target.value.trim();return;}
    if(e.target.id!=='logo-upload'||!e.target.files[0])return;
    const f=e.target.files[0], token=session;$('#logo-error').textContent='';
    if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>2*1024*1024){$('#logo-error').textContent='Choose a PNG, JPEG or WebP image no larger than 2 MB.';e.target.value='';return;}
    logoLoading=true;
    try{const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f);});await new Promise((resolve,reject)=>{const i=new Image();i.onload=resolve;i.onerror=reject;i.src=data;});if(token!==session)return;logoDraft=data;$('#logo-url').value='';$('#logo-edit-preview').innerHTML=`<span class="company-logo large"><img src="${escape(data)}" alt="Selected company logo preview"></span>`;}catch{if(token===session)$('#logo-error').textContent='This file could not be read as an image.';}finally{if(token===session)logoLoading=false;}
  });
  $('#profile-editor-body').addEventListener('submit',e=>{e.preventDefault();if(!editContext)return;$('#profile-error').textContent='';if(logoLoading){$('#profile-error').textContent='Wait for the logo preview to finish loading.';return;}
    const contacts={};for(const input of document.querySelectorAll('[data-contact]')){const value=input.value.trim();if(value&&!channelURL(input.dataset.contact,value)){$('#profile-error').textContent='Use complete http(s) URLs, or @handles for Instagram and X.';input.focus();return;}contacts[input.dataset.contact]=value;}
    let next;
    if(editContext.kind==='company'){if(logoDraft&&!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(logoDraft)&&!safeURL(logoDraft)){$('#profile-error').textContent='Use a valid http(s) logo URL or upload an image.';return;}next={...state,companies:{...state.companies,[editContext.id]:{contacts,logo:logoDraft}}};}
    else{const name=$('#person-name').value.trim();if(!name){$('#profile-error').textContent='Enter a name.';return;}const id=editContext.id||'person-'+crypto.randomUUID(),old=people().find(p=>p.id===id)||{};const person={...old,id,name,role:$('#person-role').value.trim(),companyId:$('#person-company').value,notes:$('#person-notes').value.trim(),contacts,origin:'User-edited metadata'};next={...state,people:{...state.people,[id]:person}};currentPerson=id;}
    if(write(next)){$('#profile-editor').close();refresh();renderPeople();}
  });
  return {logo,companyDetails,renderPeople,companyPeopleMarkup};
};
