"""Collection-status labels for a known publisher/resource.

Derived at runtime. Never a completeness score. INTENTIONALLY_EXCLUDED
preserves an explicit operator reason; nothing here auto-onboards a Source.
"""

from __future__ import annotations

COLLECTED = "COLLECTED"
KNOWN_NOT_COLLECTED = "KNOWN_NOT_COLLECTED"
UNKNOWN_SOURCE_IDENTITY = "UNKNOWN_SOURCE_IDENTITY"
INTENTIONALLY_EXCLUDED = "INTENTIONALLY_EXCLUDED"

COLLECTION_STATUSES = (
    COLLECTED,
    KNOWN_NOT_COLLECTED,
    UNKNOWN_SOURCE_IDENTITY,
    INTENTIONALLY_EXCLUDED,
)

COLLECTION_STATUS_LABELS = {
    COLLECTED: "COLLECTED",
    KNOWN_NOT_COLLECTED: "KNOWN / NOT COLLECTED",
    UNKNOWN_SOURCE_IDENTITY: "UNKNOWN SOURCE IDENTITY",
    INTENTIONALLY_EXCLUDED: "INTENTIONALLY EXCLUDED",
}
